name: 'Terraform Apply for kubernetes cluster in AWS using Vault secrets - works on changes in a PR'
description: 'This action will perform kubernetes cluster deployment in AWS account using Terraform using secrets in Hashicorp Vault.'
author: Paresh Deshmukh
branding:
  icon: globe
  color: purple
inputs:
  tf-working-dir:
    required: true
    description: 'Terraform working directory'
  terraform-version:
    required: true
    description: 'Terraform version'
  cluster-name:
    required: true
    description: 'Name of the kubernetes cluster'
  aws-role-to-assume:
    required: true
    description: 'Role ARN in AWS with which the connection to AWS will be established'
  aws-region:
    required: true
    description: 'AWS region'
  vault-github-token:
    required: true
    description: 'GitHub Token used for accessing Vault'
  github-token:
    required: true
    description: 'Pass secret GITHUB_TOKEN'
  github-user:
    required: false
    description: GitHub user handle for whom the SSH key is passed for cloning the remote repo
  private-ssh-key:
    required: false
    description: ssh key to clone the terraform modules from the remote repo
  pr-dir:
    required: false
    description: 'full path of a directory in a PR to filter for the terraform apply'
    
outputs:
  tf-fmt-outcome:
    description: Outcome of the 'terraform fmt' command
    value: ${{ steps.fmt.outcome }}
  tf-validate-outcome:
    description: Outcome of the 'terraform validate' command
    value: ${{ steps.validate.outcome }}
  tf-validate-output:
    description: Output of the 'terraform validate' command
    value: ${{ steps.validate.outputs.stdout }}
  tf-init-outcome:
    description: Outcome of the 'terraform init' command
    value: ${{ steps.init.outcome }}
  tf-plan-output:
    description: Output of the 'terraform plan' command
    value: ${{ steps.plan.outputs.stdout }}
    
runs:
  using: "composite"
  steps:
    # install kops
    - name: install kops
      shell: bash
      run: |
        curl -Lo kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
        chmod +x kops
        sudo mv kops /usr/local/bin/kops
    
    # install aws cli
    - name: install aws cli
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        
    # setup the latest version of the vault CLI. 
    - name: Setup Vault CLI 
      uses: eLco/setup-vault@v1.0.1
    
    # setup kubectl
    - name: install kubectl
      shell: bash
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
        echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
        
        chmod +x kubectl
        mkdir -p ~/.local/bin
        mv ./kubectl ~/.local/bin/kubectl
        
        kubectl version --client
    
    # install terraform version
    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.0
      with:
        # The version of Terraform CLI to install
        terraform_version: ${{ inputs.terraform-version }}

    - name: Get the targets for terraform plan and apply
      id: get-targets
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: |
        echo "Get the string of the targets to pass it to the terraform plan and apply"

        export files_changed=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files.[].path')
        echo "Files changed in a PR:" $files_changed
        
        chmod +x $GITHUB_ACTION_PATH/get-tf-targets.sh
        
        targets=$(sh $GITHUB_ACTION_PATH/get-tf-targets.sh "${files_changed[@]}" ${{ inputs.pr-dir }})
        
        echo "targets: " $targets
        
        echo ::set-output name=targets::$targets

    - name: Vault Login
      shell: bash
      run: vault login -address=https://vault.${{ inputs.cluster-name }}/ -method=github token=${{ inputs.vault-github-token }}
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        aws-region: ${{ inputs.aws-region }}

    - name: export kops config
      shell: bash
      run: |
        kops export kubeconfig --name ${{ inputs.cluster-name }} --state s3://kops-${{ inputs.cluster-name }} --admin
        # Shows which is the active context
        kubectl config current-context

        # Allows you to switch between contexts using their name
        kubectl config use-context ${{ inputs.cluster-name }}
    
    #check for the format
    - name: Terraform fmt
      id: fmt
      shell: bash
      continue-on-error: true
      run: |
        cd ${PWD}/${{ inputs.tf-working-dir }}
        echo "terraform fmt -check"
        terraform fmt -check
      
    
    - name: Add ssh keys for ssh-agent
      continue-on-error: false
      shell: bash
      run: |
        SSH_PATH="$HOME/.ssh"
        mkdir -p "$SSH_PATH"
        touch "$SSH_PATH/id_rsa"
        chmod 600 "$SSH_PATH/id_rsa"
        echo "${{ inputs.SSH_PRIVATE_KEY }}" > "$SSH_PATH/id_rsa"
        chmod 700 "$SSH_PATH"
        
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        
        chmod 600 "$SSH_PATH/known_hosts"
        chmod 600 "$SSH_PATH/id_rsa"
        
        eval $(ssh-agent)
        ssh-add "$SSH_PATH/id_rsa"
        
        u=${{ inputs.github-user }}
        ukeys="$(curl -sL https://github.com/${u}.keys)"
        echo "Getting ssh keys for GitHub user ${u}: ${ukeys}"
        if [[ ! "${ukeys}" =~ ^ssh- ]]; then
          echo "ssh keys for user ${u} do not begin with \"ssh-\", got \"${ukeys}\""
        fi
        
        echo "Adding ssh keys for GitHub user ${u} to ~/authorized_keys"
        echo "${ukeys}" >> ~/authorized_keys
        echo "Adding ssh keys for GitHub user ${u} to ~/authorized_keys: done"

        ssh-add -l -E sha256
        echo "SSH_AUTH_SOCK: $SSH_AUTH_SOCK"
        
        ssh -T git@github.com
        
        cd ${PWD}/${{ inputs.tf-working-dir }}
        pwd
        echo "terraform init"
        terraform init 
        
        
    - id: init
      name: Terraform Init
      shell: bash
      if: 1 == 2
      run : |
        cd ${PWD}/${{ inputs.tf-working-dir }}
        pwd
        echo "terraform init"
        terraform init 
    
    # terraform validate
    - name: Terraform Validate
      id: validate
      shell: bash
      continue-on-error: true
      run: |
        cd ${PWD}/${{ inputs.tf-working-dir }}
        pwd
        terraform validate -no-color
      
    # Run terraform plan 
    - name: terraform plan
      id: plan
      shell: bash
      run: |
        echo "Run terraform plan and get the output."
        cd ${PWD}/${{ inputs.tf-working-dir }}
        pwd
        terraform plan -lock=false -no-color ${{ steps.get-targets.outputs.targets }}
           
    # Terraform apply
    - name: Terraform apply
      id: apply
      shell: bash
      run: |
        echo "Run terraform apply."
        cd ${PWD}/${{ inputs.tf-working-dir }}
        pwd
        terraform apply -auto-approve ${{ steps.get-targets.outputs.targets }}
